/*
 * using dbDesign9
 *
 * login.length() > 3
 * senha.length() > 7
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

public class AlterarUsuario extends javax.swing.JFrame {

    private Connection conn;
    private Statement stmt;
    private PreparedStatement prepStmt;
    private ResultSet rs;

    /**
     * Vector is deprecated, but DefaultComboBoxModel uses it internally, and DefaultComboBoxModel
     * is recommended to be used in this situation, so there's no point in using something else here
     * because DefaultComboBoxModel will implement it as a Vector internally.
     */
    private Vector comboBoxUsuarioDataList;
    private AutoComboBox comboBoxUsuario;
    private Vector comboBoxNovoTipoDeUsuarioDataList;
    private AutoComboBox comboBoxNovoTipoDeUsuario;

    public AlterarUsuario() {
        comboBoxUsuarioDataList = new Vector();
        comboBoxUsuario = new AutoComboBox(comboBoxUsuarioDataList);
        comboBoxNovoTipoDeUsuarioDataList = new Vector();
        comboBoxNovoTipoDeUsuario = new AutoComboBox(comboBoxNovoTipoDeUsuarioDataList);

        initComponents();

        try {
            conn = DriverManager.getConnection("jdbc:sqlite:local/designedDb.db");
            stmt = conn.createStatement();
            stmt.setQueryTimeout(30);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        //populate comboBoxBuscarUsuario
        comboBoxUsuarioDataList.add(new LoginTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_LOGIN"
                    + " ORDER BY LOG_LOGIN");
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                LoginTable current = new LoginTable(
                        rs.getInt("LOG_ID"),
                        rs.getString("LOG_LOGIN"),
                        rs.getString("LOG_PASSWORD"),
                        rs.getString("LOG_NOTES"),
                        rs.getInt("LOG_ACTIVE"),
                        rs.getInt("LOG_TB_USER_TYPE_ID")
                );

                //getting the userType description of the current login
                prepStmt = conn.prepareStatement("SELECT USE_TYP_DESCRIPTION"
                        + " FROM TB_USER_TYPE"
                        + " WHERE USE_TYP_ID = ?"); //1
                prepStmt.setInt(1, current.getTbUserTypeId());
                current.setUserTypeDescription(prepStmt.executeQuery().getString("USE_TYP_DESCRIPTION"));

                comboBoxUsuarioDataList.add(current);
            }

            comboBoxUsuario.setDataList(comboBoxUsuarioDataList);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        //populate comboBoxNovoTipoDeUsuario
        comboBoxNovoTipoDeUsuarioDataList.add(new UserTypeTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_USER_TYPE"
                    + " WHERE USE_TYP_ACTIVE = ?" //1
                    + " ORDER BY USE_TYP_DESCRIPTION");
            prepStmt.setInt(1, 1);
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                comboBoxNovoTipoDeUsuarioDataList.add(new UserTypeTable(
                        rs.getInt("USE_TYP_ID"),
                        rs.getString("USE_TYP_DESCRIPTION"),
                        rs.getString("USE_TYP_NOTES"),
                        rs.getInt("USE_TYP_ACTIVE")
                ));
            }

            comboBoxNovoTipoDeUsuario.setDataList(comboBoxNovoTipoDeUsuarioDataList);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFinalizarAlteracao = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        labelNovoLogin = new javax.swing.JLabel();
        labelNovaSenha = new javax.swing.JLabel();
        textFieldNovoLogin = new javax.swing.JTextField();
        textFieldNovaSenha = new javax.swing.JTextField();
        labelNovasAnotacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaNovasAnotacoes = new javax.swing.JTextArea();
        comboBoxNovoTipoDeUsuario = comboBoxNovoTipoDeUsuario = new AutoComboBox(comboBoxNovoTipoDeUsuarioDataList);
        labelNovoTipoDeUsuario = new javax.swing.JLabel();
        buttonCancelarAlteracao = new javax.swing.JButton();
        labelUsuarioAtivo = new javax.swing.JLabel();
        checkBoxUsuarioAtivo = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelUsuario = new javax.swing.JLabel();
        comboBoxUsuario = comboBoxUsuario = new AutoComboBox(comboBoxUsuarioDataList);
        buttonBuscar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        labelTipoDeUsuarioAtual = new javax.swing.JLabel();
        labelValueTipoDeUsuarioAtual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonFinalizarAlteracao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonFinalizarAlteracao.setText("Finalizar Alteração");
        buttonFinalizarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarAlteracaoActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitle.setText("Alterar Usuário do Sistema");

        labelNovoLogin.setText("* Novo Login :");

        labelNovaSenha.setText("* Nova Senha :");

        labelNovasAnotacoes.setText("Novas Anotações :");

        textAreaNovasAnotacoes.setColumns(20);
        textAreaNovasAnotacoes.setRows(5);
        jScrollPane1.setViewportView(textAreaNovasAnotacoes);

        comboBoxNovoTipoDeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxNovoTipoDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNovoTipoDeUsuarioActionPerformed(evt);
            }
        });

        labelNovoTipoDeUsuario.setText("Novo Tipo de Usuário :");

        buttonCancelarAlteracao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCancelarAlteracao.setText("Cancelar Alteração");
        buttonCancelarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarAlteracaoActionPerformed(evt);
            }
        });

        labelUsuarioAtivo.setText("Usuário Ativo :");

        labelUsuario.setText("* Usuário :");

        comboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxUsuarioActionPerformed(evt);
            }
        });

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        labelTipoDeUsuarioAtual.setText("Tipo de Usuário Atual :");

        labelValueTipoDeUsuarioAtual.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNovoLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNovoLogin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNovasAnotacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNovoTipoDeUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxNovoTipoDeUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNovaSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNovaSenha)))))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCancelarAlteracao)
                .addGap(31, 31, 31)
                .addComponent(buttonFinalizarAlteracao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsuarioAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxUsuarioAtivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonBuscar))
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTipoDeUsuarioAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelValueTipoDeUsuarioAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelTitle)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonBuscar)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovoLogin)
                    .addComponent(textFieldNovoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovaSenha)
                    .addComponent(textFieldNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuarioAtivo)
                    .addComponent(checkBoxUsuarioAtivo))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoDeUsuarioAtual)
                    .addComponent(labelValueTipoDeUsuarioAtual))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxNovoTipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNovoTipoDeUsuario))
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNovasAnotacoes)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonFinalizarAlteracao)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCancelarAlteracao)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinalizarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarAlteracaoActionPerformed
        comboBoxNovoTipoDeUsuarioActionPerformed(evt); //to make sure it's selected

        LoginTable selectedLogin = (LoginTable) comboBoxUsuario.getSelectedItem();

        trimMandatoryFields();

        if (selectedLogin.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Alteração\", favor selecionar uma categoria de filme, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (textFieldNovoLogin.getText().isEmpty()
                || textFieldNovaSenha.getText().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nOs campos * são obrigatórios!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (textFieldNovoLogin.getText().length() < 4) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nO login precisa ter mais de 3 caracteres!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (textFieldNovaSenha.getText().length() < 8) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nA senha precisa ter mais de 7 caracteres!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (!textFieldNovoLogin.getText().equals(selectedLogin.getLogin())
                && comboBoxUsuarioContainsLogin(textFieldNovoLogin.getText())) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nO Login \"" + textFieldNovoLogin.getText() + "\" não está disponível!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja finalizar?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                UserTypeTable selectedUserType = (UserTypeTable) comboBoxNovoTipoDeUsuario.getSelectedItem();

                //updating TB_LOGIN
                prepStmt = conn.prepareStatement("UPDATE TB_LOGIN SET"
                        + " LOG_LOGIN = ?," //1
                        + " LOG_PASSWORD = ?," //2
                        + " LOG_NOTES = ?," //3
                        + " LOG_ACTIVE = ?," //4
                        + " LOG_TB_USER_TYPE_ID = ?" //5
                        + " WHERE LOG_ID = ?"); //6
                prepStmt.setString(1, textFieldNovoLogin.getText());
                prepStmt.setString(2, textFieldNovaSenha.getText());
                prepStmt.setString(3, textAreaNovasAnotacoes.getText());
                prepStmt.setInt(4, checkBoxUsuarioAtivo.isSelected() ? 1 : 0);
                prepStmt.setInt(5,
                        !selectedUserType.isEmptyString() //if some userType is selected
                        ? selectedUserType.getId() //userType changed
                        : selectedLogin.getTbUserTypeId() //userType didnt change
                );
                prepStmt.setInt(6, selectedLogin.getId());
                prepStmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Alteração do Usuário bem sucedida.");
                new AdminGerenciadorDeEmprestimosDeFilmes().setVisible(true);
                super.dispose();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonFinalizarAlteracaoActionPerformed

    private void buttonCancelarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarAlteracaoActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarAlteracaoActionPerformed

    private void comboBoxNovoTipoDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNovoTipoDeUsuarioActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxNovoTipoDeUsuarioActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        comboBoxUsuarioActionPerformed(evt); //to make sure it's selected

        LoginTable selectedLogin = (LoginTable) comboBoxUsuario.getSelectedItem();

        if (selectedLogin.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor selecionar um usuário para \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            textFieldNovoLogin.setText(selectedLogin.getLogin());
            textFieldNovaSenha.setText(selectedLogin.getPassword());
            checkBoxUsuarioAtivo.setSelected(selectedLogin.getActive() == 1);
            labelValueTipoDeUsuarioAtual.setText(selectedLogin.getUserTypeDescription());
            textAreaNovasAnotacoes.setText(selectedLogin.getNotes());
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void comboBoxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxUsuarioActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxUsuarioActionPerformed

    /**
     * checking if the login is already present in the comboBox list.
     * this comboBox list has all the logins from the DB, logins that are active and
     * inactive, therefore is the same as searching the DB, but faster.
     *
     * is not nice to have to create a LoginTable object just to compare their login
     * attribute, therefore it wouldn't work if i used a custom equals(), that compares their
     * login attribute, in the LoginTable object.
     *
     * @param login
     * @return
     */
    private boolean comboBoxUsuarioContainsLogin(String login) {
        for (int i = 0; i < comboBoxUsuarioDataList.size(); i++) {
            LoginTable currentLogin = (LoginTable) comboBoxUsuarioDataList.get(i);

            if (!currentLogin.isEmptyString()
                    && currentLogin.getLogin().equals(login)) {

                return true;
            }
        }

        return false;
    }

    /**
     * trimming the fields that are mandatory\obligatory, meaning the fields that have an "*"
     * preceding their label.
     */
    private void trimMandatoryFields() {
        textFieldNovoLogin.setText(textFieldNovoLogin.getText().trim());
        textFieldNovaSenha.setText(textFieldNovaSenha.getText().trim());
    }

    /**
     * custom dispose() to ask if the user is sure, close the DB connection and call the main GUI
     * again.
     */
    @Override
    public void dispose() {
        if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja sair?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            new AdminGerenciadorDeEmprestimosDeFilmes().setVisible(true);
            super.dispose();
        }
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
         * feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCancelarAlteracao;
    private javax.swing.JButton buttonFinalizarAlteracao;
    private javax.swing.JCheckBox checkBoxUsuarioAtivo;
//    private javax.swing.JComboBox<String> comboBoxNovoTipoDeUsuario;
  //  private javax.swing.JComboBox<String> comboBoxUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelNovaSenha;
    private javax.swing.JLabel labelNovasAnotacoes;
    private javax.swing.JLabel labelNovoLogin;
    private javax.swing.JLabel labelNovoTipoDeUsuario;
    private javax.swing.JLabel labelTipoDeUsuarioAtual;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelUsuarioAtivo;
    private javax.swing.JLabel labelValueTipoDeUsuarioAtual;
    private javax.swing.JTextArea textAreaNovasAnotacoes;
    private javax.swing.JTextField textFieldNovaSenha;
    private javax.swing.JTextField textFieldNovoLogin;
    // End of variables declaration//GEN-END:variables
}
