/*
 * using dbDesign9
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

public class AlterarCategoriaDeFilme extends javax.swing.JFrame {

    private Connection conn;
    private Statement stmt;
    private PreparedStatement prepStmt;
    private ResultSet rs;

    /**
     * Vector is deprecated, but DefaultComboBoxModel uses it internally, and DefaultComboBoxModel
     * is recommended to be used in this situation, so there's no point in using something else here
     * because DefaultComboBoxModel will implement it as a Vector internally.
     */
    private Vector comboBoxCategoriaDeFilmeDataList;
    private AutoComboBox comboBoxCategoriaDeFilme;

    public AlterarCategoriaDeFilme() {
        comboBoxCategoriaDeFilmeDataList = new Vector();
        comboBoxCategoriaDeFilme = new AutoComboBox(comboBoxCategoriaDeFilmeDataList);

        initComponents();

        try {
            conn = DriverManager.getConnection("jdbc:sqlite:local/designedDb.db");
            stmt = conn.createStatement();
            stmt.setQueryTimeout(30);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        comboBoxCategoriaDeFilmeDataList.add(new MovieCategoryTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_MOVIE_CATEGORY"
                    + " ORDER BY MOV_CAT_DESCRIPTION");
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                comboBoxCategoriaDeFilmeDataList.add(new MovieCategoryTable(
                        rs.getInt("MOV_CAT_ID"),
                        rs.getString("MOV_CAT_DESCRIPTION"),
                        rs.getString("MOV_CAT_NOTES"),
                        rs.getInt("MOV_CAT_ACTIVE"),
                        false //the flag "toInsert" wont be used in this GUI
                ));
            }
            comboBoxCategoriaDeFilme.setDataList(comboBoxCategoriaDeFilmeDataList);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelNovaDescricao = new javax.swing.JLabel();
        textFieldNovaDescricao = new javax.swing.JTextField();
        labelNovasAnotacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaNovasAnotacoes = new javax.swing.JTextArea();
        buttonCancelarAlteracao = new javax.swing.JButton();
        buttonFinalizarAlteracao = new javax.swing.JButton();
        labelCategoriaDeFilmeAtiva = new javax.swing.JLabel();
        checkBoxCategoriaDeFilmeAtiva = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelCategoriaDeFilme = new javax.swing.JLabel();
        comboBoxCategoriaDeFilme = comboBoxCategoriaDeFilme = new AutoComboBox(comboBoxCategoriaDeFilmeDataList);
        buttonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitle.setText("Alterar Categoria de Filme");

        labelNovaDescricao.setText("* Nova Descrição :");

        labelNovasAnotacoes.setText("Novas Anotações :");

        textAreaNovasAnotacoes.setColumns(20);
        textAreaNovasAnotacoes.setRows(5);
        jScrollPane1.setViewportView(textAreaNovasAnotacoes);

        buttonCancelarAlteracao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCancelarAlteracao.setText("Cancelar Alteração");
        buttonCancelarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarAlteracaoActionPerformed(evt);
            }
        });

        buttonFinalizarAlteracao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonFinalizarAlteracao.setText("Finalizar Alteração");
        buttonFinalizarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarAlteracaoActionPerformed(evt);
            }
        });

        labelCategoriaDeFilmeAtiva.setText("Categoria de Filme Ativa :");

        labelCategoriaDeFilme.setText("* Categoria de Filme :");

        comboBoxCategoriaDeFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCategoriaDeFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoriaDeFilmeActionPerformed(evt);
            }
        });

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNovaDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldNovaDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNovasAnotacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCategoriaDeFilmeAtiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxCategoriaDeFilmeAtiva)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCategoriaDeFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxCategoriaDeFilme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(buttonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCancelarAlteracao)
                        .addGap(31, 31, 31)
                        .addComponent(buttonFinalizarAlteracao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoriaDeFilme)
                    .addComponent(comboBoxCategoriaDeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovaDescricao)
                    .addComponent(textFieldNovaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoriaDeFilmeAtiva)
                    .addComponent(checkBoxCategoriaDeFilmeAtiva))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNovasAnotacoes)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelarAlteracao)
                    .addComponent(buttonFinalizarAlteracao))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinalizarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarAlteracaoActionPerformed
        MovieCategoryTable selectedMovieCategory = (MovieCategoryTable) comboBoxCategoriaDeFilme.getSelectedItem();

        //trimming
        textFieldNovaDescricao.setText(textFieldNovaDescricao.getText().trim());

        if (selectedMovieCategory.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Alteração\", favor selecionar uma categoria de filme, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (textFieldNovaDescricao.getText().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nOs campos * são obrigatórios!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (!textFieldNovaDescricao.getText().equals(selectedMovieCategory.getDescription())
                && comboBoxCategoriaDeFilmeContainsDescription(textFieldNovaDescricao.getText())) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nJá existe uma categoria de filme chamada \"" + textFieldNovaDescricao.getText() + "\" !",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja finalizar?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                //updating TB_MOVIE_CATEGORY
                prepStmt = conn.prepareStatement("UPDATE TB_MOVIE_CATEGORY SET"
                        + " MOV_CAT_DESCRIPTION = ?," //1
                        + " MOV_CAT_NOTES = ?," //2
                        + " MOV_CAT_ACTIVE = ?" //3
                        + " WHERE MOV_CAT_ID = ?"); //4
                prepStmt.setString(1, textFieldNovaDescricao.getText());
                prepStmt.setString(2, textAreaNovasAnotacoes.getText());
                prepStmt.setInt(3, checkBoxCategoriaDeFilmeAtiva.isSelected() ? 1 : 0);
                prepStmt.setInt(4, selectedMovieCategory.getId());
                prepStmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Alteração da Categoria de Filme bem sucedida.");
                new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
                super.dispose();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonFinalizarAlteracaoActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        comboBoxCategoriaDeFilmeActionPerformed(evt); //to make sure it's selected

        MovieCategoryTable selectedMovieCategory = (MovieCategoryTable) comboBoxCategoriaDeFilme.getSelectedItem();

        if (selectedMovieCategory.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor selecionar uma categoria de filme para \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            textFieldNovaDescricao.setText(selectedMovieCategory.getDescription());
            checkBoxCategoriaDeFilmeAtiva.setSelected(selectedMovieCategory.getActive() == 1);
            textAreaNovasAnotacoes.setText(selectedMovieCategory.getNotes());
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonCancelarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarAlteracaoActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarAlteracaoActionPerformed

    private void comboBoxCategoriaDeFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoriaDeFilmeActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxCategoriaDeFilmeActionPerformed

    /**
     * checking if the description is already present in the comboBox list.
     * this comboBox list has all the movieCategories from the DB, movieCategories that are active
     * and inactive, therefore is the same as searching the DB, but faster.
     *
     * is not nice to have to create a MovieCategoryTable object just to compare their description
     * attribute, therefore it wouldn't work if i used a custom equals(), that compares their
     * description attribute, in the MovieCategoryTable object.
     *
     * @param description
     * @return
     */
    private boolean comboBoxCategoriaDeFilmeContainsDescription(String description) {
        for (int i = 0; i < comboBoxCategoriaDeFilmeDataList.size(); i++) {
            MovieCategoryTable currentMovieCategory = (MovieCategoryTable) comboBoxCategoriaDeFilmeDataList.get(i);

            if (!currentMovieCategory.isEmptyString()
                    && currentMovieCategory.getDescription().equals(description)) {

                return true;
            }
        }

        return false;
    }

    /**
     * custom dispose() to ask if the user is sure, close the DB connection and call the main GUI
     * again.
     */
    @Override
    public void dispose() {
        if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja sair?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
            super.dispose();
        }
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
         * feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDeFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDeFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDeFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDeFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarCategoriaDeFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCancelarAlteracao;
    private javax.swing.JButton buttonFinalizarAlteracao;
    private javax.swing.JCheckBox checkBoxCategoriaDeFilmeAtiva;
//    private javax.swing.JComboBox<String> comboBoxCategoriaDeFilme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelCategoriaDeFilme;
    private javax.swing.JLabel labelCategoriaDeFilmeAtiva;
    private javax.swing.JLabel labelNovaDescricao;
    private javax.swing.JLabel labelNovasAnotacoes;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextArea textAreaNovasAnotacoes;
    private javax.swing.JTextField textFieldNovaDescricao;
    // End of variables declaration//GEN-END:variables
}
