/*
 * using dbDesign9
 */

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class AlterarCategoriaDePreco extends javax.swing.JFrame {

    private Connection conn;
    private Statement stmt;
    private PreparedStatement prepStmt;
    private ResultSet rs;

    /**
     * Vector is deprecated, but DefaultComboBoxModel uses it internally, and DefaultComboBoxModel
     * is recommended to be used in this situation, so there's no point in using something else here
     * because DefaultComboBoxModel will implement it as a Vector internally.
     */
    private Vector comboBoxCategoriaDePrecoDataList;
    private AutoComboBox comboBoxCategoriaDePreco;
    private Vector comboBoxAlterarFilmesDataList;
    private AutoComboBox comboBoxAlterarFilmes;
    private DefaultListModel listPrecosModel;

    private ArrayList<PriceTable> pricesToRemoveFromDB;

    public AlterarCategoriaDePreco() {
        comboBoxCategoriaDePrecoDataList = new Vector();
        comboBoxCategoriaDePreco = new AutoComboBox(comboBoxCategoriaDePrecoDataList);
        comboBoxAlterarFilmesDataList = new Vector();
        comboBoxAlterarFilmes = new AutoComboBox(comboBoxAlterarFilmesDataList);

        initComponents();

        listPrecosModel = new DefaultListModel();
        listPrecos.setModel(listPrecosModel);

        pricesToRemoveFromDB = new ArrayList<PriceTable>();

        try {
            conn = DriverManager.getConnection("jdbc:sqlite:local/designedDb.db");
            stmt = conn.createStatement();
            stmt.setQueryTimeout(30);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        //populate comboBoxCategoriaDePreco and comboBoxAlterarFilmes
        comboBoxCategoriaDePrecoDataList.add(new PriceCategoryTable()); //insert the first empty string
        comboBoxAlterarFilmesDataList.add(new PriceCategoryTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_PRICE_CATEGORY"
                    + " ORDER BY PRI_CAT_DESCRIPTION");
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                PriceCategoryTable currentPriceCategory = new PriceCategoryTable(
                        rs.getInt("PRI_CAT_ID"),
                        rs.getString("PRI_CAT_DESCRIPTION"),
                        rs.getString("PRI_CAT_NOTES"),
                        rs.getInt("PRI_CAT_AMOUNT_OF_MOVIES_USING"),
                        rs.getInt("PRI_CAT_ACTIVE"),
                        rs.getLong("PRI_CAT_FINE_PRICE"),
                        rs.getInt("PRI_CAT_MULTIPLY_BY")
                );
                comboBoxCategoriaDePrecoDataList.add(currentPriceCategory);
                comboBoxAlterarFilmesDataList.add(currentPriceCategory);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        comboBoxCategoriaDePreco.setDataList(comboBoxCategoriaDePrecoDataList);
        comboBoxAlterarFilmes.setDataList(comboBoxAlterarFilmesDataList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        buttonFinalizarAlteracao = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        labelNovaDescricao = new javax.swing.JLabel();
        labelNovasAnotacoes = new javax.swing.JLabel();
        textFieldNovaDescricao = new javax.swing.JTextField();
        labelNovoPreco = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaNovasAnotacoes = new javax.swing.JTextArea();
        labelPrecos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPrecos = new javax.swing.JList<>();
        buttonAdicionarPreco = new javax.swing.JButton();
        buttonRemoverPreco = new javax.swing.JButton();
        labelDias = new javax.swing.JLabel();
        labelValueDias = new javax.swing.JLabel();
        buttonMenosDias = new javax.swing.JButton();
        buttonMaisDias = new javax.swing.JButton();
        labelValor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelCategoriaDePreco = new javax.swing.JLabel();
        comboBoxCategoriaDePreco = new AutoComboBox(comboBoxCategoriaDePrecoDataList);
        labelCategoriaDePrecoAtiva = new javax.swing.JLabel();
        checkBoxCategoriaDePrecoAtiva = new javax.swing.JCheckBox();
        labelAlterarFilmesComEstaCategoriaPara = new javax.swing.JLabel();
        comboBoxAlterarFilmes = new AutoComboBox(comboBoxAlterarFilmesDataList);
        buttonBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        buttonCancelarAlteracao = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        labelDevolucaoAtrasada = new javax.swing.JLabel();
        labelPrecosDosDiasMultiplicadosPor = new javax.swing.JLabel();
        labelValorDaMulta = new javax.swing.JLabel();
        buttonPrecosMultiplicadosMenos = new javax.swing.JButton();
        labelValuePrecosDosDiasMultiplicadosPor = new javax.swing.JLabel();
        buttonPrecosMultiplicadosMais = new javax.swing.JButton();
        labelQuantidadeDeFilmesUsandoEstaCategoria = new javax.swing.JLabel();
        labelValueQuantidadeDeFilmesUsandoEstaCategoria = new javax.swing.JLabel();
        formattedTextFieldValor = new javax.swing.JFormattedTextField();
        formattedTextFieldFinePrice = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(814, 667));

        jPanel1.setPreferredSize(new java.awt.Dimension(814, 907));

        buttonFinalizarAlteracao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonFinalizarAlteracao.setText("Finalizar Alteração");
        buttonFinalizarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarAlteracaoActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitle.setText("Alterar Categoria de Preço");

        labelNovaDescricao.setText("* Nova Descrição :");

        labelNovasAnotacoes.setText("Novas Anotações :");

        labelNovoPreco.setText("Novo Preço :");

        textAreaNovasAnotacoes.setColumns(20);
        textAreaNovasAnotacoes.setRows(5);
        jScrollPane2.setViewportView(textAreaNovasAnotacoes);

        labelPrecos.setText("* Preços :");

        listPrecos.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        listPrecos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listPrecos);

        buttonAdicionarPreco.setText("Adicionar Preço");
        buttonAdicionarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarPrecoActionPerformed(evt);
            }
        });

        buttonRemoverPreco.setText("Remover Preço");
        buttonRemoverPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverPrecoActionPerformed(evt);
            }
        });

        labelDias.setText("Dias :");

        labelValueDias.setText("0");

        buttonMenosDias.setText("-");
        buttonMenosDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenosDiasActionPerformed(evt);
            }
        });

        buttonMaisDias.setText("+");
        buttonMaisDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMaisDiasActionPerformed(evt);
            }
        });

        labelValor.setText("Valor :    R$");

        jLabel1.setText("  Dias                     Preço  R$                                                Dias Atrasados                      Preço de Cada Dia Atrasado");

        labelCategoriaDePreco.setText("* Categoria de Preço :");

        comboBoxCategoriaDePreco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCategoriaDePreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoriaDePrecoActionPerformed(evt);
            }
        });

        labelCategoriaDePrecoAtiva.setText("Categoria de Preço Ativa :");

        labelAlterarFilmesComEstaCategoriaPara.setText("Alterar Filmes Com Esta Categoria Para :");

        comboBoxAlterarFilmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxAlterarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAlterarFilmesActionPerformed(evt);
            }
        });

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonCancelarAlteracao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCancelarAlteracao.setText("Cancelar Alteração");
        buttonCancelarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarAlteracaoActionPerformed(evt);
            }
        });

        labelDevolucaoAtrasada.setText("Devolução Atrasada :");

        labelPrecosDosDiasMultiplicadosPor.setText("Preços dos Dias Multiplicados por :");

        labelValorDaMulta.setText("Valor da Multa :   R$");

        buttonPrecosMultiplicadosMenos.setText("-");
        buttonPrecosMultiplicadosMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrecosMultiplicadosMenosActionPerformed(evt);
            }
        });

        labelValuePrecosDosDiasMultiplicadosPor.setText("0");

        buttonPrecosMultiplicadosMais.setText("+");
        buttonPrecosMultiplicadosMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrecosMultiplicadosMaisActionPerformed(evt);
            }
        });

        labelQuantidadeDeFilmesUsandoEstaCategoria.setText("Quantidade de Filmes (contando cada cópia) usando esta categoria :");

        labelValueQuantidadeDeFilmesUsandoEstaCategoria.setText("0");

        formattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        formattedTextFieldValor.setText("0.00");

        formattedTextFieldFinePrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        formattedTextFieldFinePrice.setText("0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAlterarFilmesComEstaCategoriaPara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxAlterarFilmes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNovaDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNovaDescricao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonRemoverPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAdicionarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelNovoPreco)
                        .addGap(18, 18, 18)
                        .addComponent(labelDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelValueDias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(buttonMenosDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMaisDias)
                        .addGap(96, 96, 96)
                        .addComponent(labelValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNovasAnotacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCancelarAlteracao)
                        .addGap(40, 40, 40)
                        .addComponent(buttonFinalizarAlteracao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCategoriaDePrecoAtiva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxCategoriaDePrecoAtiva))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDevolucaoAtrasada)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelValorDaMulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(formattedTextFieldFinePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelPrecosDosDiasMultiplicadosPor)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelValuePrecosDosDiasMultiplicadosPor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonPrecosMultiplicadosMenos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonPrecosMultiplicadosMais)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelQuantidadeDeFilmesUsandoEstaCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(labelValueQuantidadeDeFilmesUsandoEstaCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPrecos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCategoriaDePreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxCategoriaDePreco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(buttonBuscar)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoriaDePreco)
                    .addComponent(comboBoxCategoriaDePreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidadeDeFilmesUsandoEstaCategoria)
                    .addComponent(labelValueQuantidadeDeFilmesUsandoEstaCategoria))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovaDescricao)
                    .addComponent(textFieldNovaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoriaDePrecoAtiva)
                    .addComponent(checkBoxCategoriaDePrecoAtiva))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNovasAnotacoes)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNovoPreco)
                            .addComponent(labelDias)
                            .addComponent(labelValueDias)
                            .addComponent(buttonMenosDias)
                            .addComponent(buttonMaisDias)
                            .addComponent(labelValor)
                            .addComponent(formattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPrecos)
                        .addGap(263, 263, 263)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionarPreco)
                    .addComponent(buttonRemoverPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDevolucaoAtrasada)
                    .addComponent(labelValorDaMulta)
                    .addComponent(formattedTextFieldFinePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecosDosDiasMultiplicadosPor)
                    .addComponent(buttonPrecosMultiplicadosMenos)
                    .addComponent(labelValuePrecosDosDiasMultiplicadosPor)
                    .addComponent(buttonPrecosMultiplicadosMais))
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlterarFilmesComEstaCategoriaPara)
                    .addComponent(comboBoxAlterarFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFinalizarAlteracao)
                    .addComponent(buttonCancelarAlteracao))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinalizarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarAlteracaoActionPerformed
        PriceCategoryTable selectedPriceCategory = (PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem();
        PriceCategoryTable selectedCategoryToChangeMoviesTo = (PriceCategoryTable) comboBoxAlterarFilmes.getSelectedItem();

        //trimming a mandatory field, meaning a field that has an "*" preceding the label.
        textFieldNovaDescricao.setText(textFieldNovaDescricao.getText().trim());

        if (formattedTextFieldFinePrice.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Alteração\", favor inserir o valor da multa.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedPriceCategory.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Alteração\", favor selecionar uma categoria de preço, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (textFieldNovaDescricao.getText().isEmpty()
                || listPrecos.getModel().getSize() == 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nOs campos * são obrigatórios!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (!textFieldNovaDescricao.getText().equals(selectedPriceCategory.getDescription())
                && comboBoxCategoriaDePrecoContainsDescription(textFieldNovaDescricao.getText())) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nJá existe uma categoria de preço chamada \"" + textFieldNovaDescricao.getText() + "\" !",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldFinePrice.getText())
                .compareTo(BigDecimal.ZERO) < 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nNão é possível inserir um valor negativo!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldFinePrice.getText())
                .multiply(new BigDecimal(100))
                .compareTo(new BigDecimal(Long.MAX_VALUE)) >= 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor inserir um valor abaixo de \"R$ " + new BigDecimal(Long.MAX_VALUE).divide(new BigDecimal(100)) + "\"",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja finalizar?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                prepStmt = conn.prepareStatement("UPDATE TB_PRICE_CATEGORY SET "
                        + "PRI_CAT_DESCRIPTION = ?," //1
                        + "PRI_CAT_NOTES = ?," //2
                        + "PRI_CAT_AMOUNT_OF_MOVIES_USING = ?," //3
                        + "PRI_CAT_ACTIVE = ?," //4
                        + "PRI_CAT_FINE_PRICE = ?," //5
                        + "PRI_CAT_MULTIPLY_BY = ? " //6
                        + "WHERE PRI_CAT_ID = ?"); //7
                prepStmt.setString(1, textFieldNovaDescricao.getText());
                prepStmt.setString(2, textAreaNovasAnotacoes.getText());

                /*
                 * the PRI_CAT_AMOUNT_OF_MOVIES_USING is already changed here even though the rest
                 * of the changes, if a new priceCategory was selected, are done a few lines down.
                 * the change is done here already because if i do the change later the DB will need
                 * to find PRI_CAT_ID again just to change the PRI_CAT_AMOUNT_OF_MOVIES_USING
                 * attribute.
                 */
                prepStmt.setInt(3,
                        !selectedCategoryToChangeMoviesTo.isEmptyString()
                        && selectedCategoryToChangeMoviesTo.getId() != selectedPriceCategory.getId()
                        ? 0
                        : selectedPriceCategory.getAmountOfMoviesUsing()
                );

                prepStmt.setInt(4, checkBoxCategoriaDePrecoAtiva.isSelected() ? 1 : 0);
                prepStmt.setLong(5,
                        new BigDecimal(formattedTextFieldFinePrice.getText())
                                .multiply(new BigDecimal(100))
                                .longValue()
                );
                prepStmt.setInt(6, Integer.parseInt(labelValuePrecosDosDiasMultiplicadosPor.getText()));
                prepStmt.setInt(7, selectedPriceCategory.getId());
                prepStmt.executeUpdate();

                //insert each new price for the price category
                for (int i = 0; i < listPrecosModel.getSize(); i++) {
                    PriceTable currentPrice = (PriceTable) listPrecosModel.getElementAt(i);

                    if (currentPrice.isToInsert()) {
                        prepStmt = conn.prepareStatement("INSERT INTO TB_PRICE("
                                + "PRI_AMOUNT_OF_DAYS," //1
                                + "PRI_PRICE," //2
                                + "PRI_TB_PRICE_CATEGORY_ID" //3
                                + ") VALUES(?,?,?)");
                        prepStmt.setInt(1, currentPrice.getAmountOfDays());
                        prepStmt.setLong(2, currentPrice.getPrice());
                        prepStmt.setInt(3, selectedPriceCategory.getId());
                        prepStmt.executeUpdate();
                    }
                }

                //deleting each price that the user removed for the price category
                for (int i = 0; i < pricesToRemoveFromDB.size(); i++) {
                    prepStmt = conn.prepareStatement("DELETE"
                            + " FROM TB_PRICE"
                            + " WHERE PRI_ID = ?"); //1
                    prepStmt.setInt(1, pricesToRemoveFromDB.get(i).getId());
                    prepStmt.executeUpdate();
                }

                //if some category is selected in the comboBoxAlterarFilmes
                if (!selectedCategoryToChangeMoviesTo.isEmptyString()) {
                    if (selectedCategoryToChangeMoviesTo.getId() == selectedPriceCategory.getId()) {

                        JOptionPane.showMessageDialog(null, "A categoria de preço selecionada para ser a nova categoria nos filmes, é a mesma"
                                + "\ncategoria de preço sendo alterada, portanto não vai ser mudada.");

                    } else {
                        /*
                         * change all the movies that are using the price category selected in the
                         * comboBoxCategoriaDePreco, to the price category selected in the
                         * comboBoxAlterarFilmes.
                         */
                        prepStmt = conn.prepareStatement("UPDATE TB_MOVIE SET"
                                + " MOV_TB_PRICE_CATEGORY_ID = ?" //1
                                + " WHERE MOV_TB_PRICE_CATEGORY_ID = ?"); //2
                        prepStmt.setInt(1, selectedCategoryToChangeMoviesTo.getId());
                        prepStmt.setInt(2, selectedPriceCategory.getId());
                        prepStmt.executeUpdate();

                        /*
                         * update the PRI_CAT_AMOUNT_OF_MOVIES_USING attribute of the price
                         * category selected in the comboBoxAlterarFilmes.
                         */
                        prepStmt = conn.prepareStatement("UPDATE TB_PRICE_CATEGORY SET"
                                + " PRI_CAT_AMOUNT_OF_MOVIES_USING = ?" //1
                                + " WHERE PRI_CAT_ID = ?"); //2
                        prepStmt.setInt(1,
                                selectedCategoryToChangeMoviesTo.getAmountOfMoviesUsing()
                                + selectedPriceCategory.getAmountOfMoviesUsing()
                        );
                        prepStmt.setInt(2, selectedCategoryToChangeMoviesTo.getId());
                        prepStmt.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Alteração dos filmes bem sucedida.");
                    }
                }

                JOptionPane.showMessageDialog(null, "Alteração da Categoria de Preço bem sucedida.");
                new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
                super.dispose();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonFinalizarAlteracaoActionPerformed

    private void buttonRemoverPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverPrecoActionPerformed
        int selectedIndex = listPrecos.getSelectedIndex();

        if (((PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Preço\", favor selecionar uma categoria de preço, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedIndex == -1) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Preço\", favor selecionar um preço da lista de preços, para remover.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja remover o preço selecionado?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            PriceTable selectedPrice = (PriceTable) listPrecosModel.get(selectedIndex);

            /*
             * if is not to insert (is not a new item in the list), then it already was in the DB
             * and it must be removed from the DB as well.
             */
            if (!selectedPrice.isToInsert()) {
                pricesToRemoveFromDB.add(selectedPrice);
            }
            listPrecosModel.remove(selectedIndex);
        }
    }//GEN-LAST:event_buttonRemoverPrecoActionPerformed

    private void buttonAdicionarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarPrecoActionPerformed
        PriceCategoryTable selectedPriceCategory = (PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem();
        int amountOfDaysToInsert = Integer.parseInt(labelValueDias.getText());

        if (formattedTextFieldValor.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Adicionar Preço\", favor inserir um valor.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedPriceCategory.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Adicionar Preço\", favor selecionar uma categoria de preço, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (listPrecosContainsAmountOfDays(amountOfDaysToInsert)) {

            JOptionPane.showMessageDialog(
                    null,
                    "A lista de preços já possui um preço para " + amountOfDaysToInsert + " dia(s).",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValor.getText())
                .compareTo(BigDecimal.ZERO) < 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nNão é possível inserir um valor negativo!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValor.getText())
                .multiply(new BigDecimal(100))
                .compareTo(new BigDecimal(Long.MAX_VALUE)) >= 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor inserir um valor abaixo de \"R$ " + new BigDecimal(Long.MAX_VALUE).divide(new BigDecimal(100))
                    + "\".\nConsiderando por quanto os preços serão multiplicados no caso de devolução atrasada, o valor deve ser ainda mais baixo!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            //where the new price will be inserted, in the list of prices
            int index = 0;

            /*
             * this loop will find the place to insert the new price, if the list is empty this wont
             * loop and it will insert the new price at index = 0.
             */
            while (index < listPrecosModel.getSize()) {
                if (amountOfDaysToInsert > ((PriceTable) listPrecosModel.getElementAt(index)).getAmountOfDays()) {
                    index++;
                } else {
                    break;
                }
            }

            /*
             * insert the new price already in the right place, therefore there's no need to sort
             * the list.
             */
            listPrecosModel.add(index,
                    new PriceTable(
                            amountOfDaysToInsert,
                            new BigDecimal(formattedTextFieldValor.getText())
                                    .multiply(new BigDecimal(100))
                                    .longValue(),
                            selectedPriceCategory.getId(),
                            Integer.parseInt(labelValuePrecosDosDiasMultiplicadosPor.getText())
                    )
            );

            //reset the days and value fields
            labelValueDias.setText("0");
            formattedTextFieldValor.setText("0.00");
        }
    }//GEN-LAST:event_buttonAdicionarPrecoActionPerformed

    private void buttonMaisDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMaisDiasActionPerformed
        if (((PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor selecionar uma categoria de preço, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            labelValueDias.setText(Integer.toString(Integer.parseInt(labelValueDias.getText()) + 1));
        }
    }//GEN-LAST:event_buttonMaisDiasActionPerformed

    private void buttonMenosDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenosDiasActionPerformed
        if (((PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor selecionar uma categoria de preço, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            int currentValue = Integer.parseInt(labelValueDias.getText());
            labelValueDias.setText(Integer.toString(currentValue > 0 ? currentValue - 1 : currentValue));
        }
    }//GEN-LAST:event_buttonMenosDiasActionPerformed

    private void comboBoxCategoriaDePrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoriaDePrecoActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxCategoriaDePrecoActionPerformed

    private void buttonCancelarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarAlteracaoActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarAlteracaoActionPerformed

    private void comboBoxAlterarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAlterarFilmesActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxAlterarFilmesActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        comboBoxCategoriaDePrecoActionPerformed(evt); //to make sure it's selected.

        PriceCategoryTable selectedPriceCategory = (PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem();

        if (selectedPriceCategory.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor selecionar uma categoria de preço para \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            //load all the data of the selectedPriceCategory
            labelValueQuantidadeDeFilmesUsandoEstaCategoria.setText(
                    selectedPriceCategory.getAmountOfMoviesUsing()
                    + " filme(s)"
            );
            textFieldNovaDescricao.setText(selectedPriceCategory.getDescription());
            checkBoxCategoriaDePrecoAtiva.setSelected(selectedPriceCategory.getActive() == 1);
            textAreaNovasAnotacoes.setText(selectedPriceCategory.getNotes());
            formattedTextFieldFinePrice.setText(
                    new DecimalFormat("#0.00").format(
                            BigDecimal.valueOf(selectedPriceCategory.getFinePrice())
                                    .divide(new BigDecimal(100))
                    )
            );
            labelValuePrecosDosDiasMultiplicadosPor.setText(
                    Integer.toString(selectedPriceCategory.getMultiplyBy())
            );

            listPrecosModel.clear();
            try {
                prepStmt = conn.prepareStatement("SELECT *"
                        + " FROM TB_PRICE"
                        + " WHERE PRI_TB_PRICE_CATEGORY_ID = ?" //1
                        + " ORDER BY PRI_AMOUNT_OF_DAYS");
                prepStmt.setInt(1, selectedPriceCategory.getId());
                rs = prepStmt.executeQuery();

                while (rs.next()) {
                    listPrecosModel.addElement(new PriceTable(
                            rs.getInt("PRI_ID"),
                            rs.getInt("PRI_AMOUNT_OF_DAYS"),
                            rs.getLong("PRI_PRICE"),
                            rs.getInt("PRI_TB_PRICE_CATEGORY_ID"),
                            selectedPriceCategory.getMultiplyBy()
                    ));
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonPrecosMultiplicadosMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrecosMultiplicadosMenosActionPerformed
        if (((PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor selecionar uma categoria de preço, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            int currentValue = Integer.parseInt(labelValuePrecosDosDiasMultiplicadosPor.getText());

            labelValuePrecosDosDiasMultiplicadosPor.setText(
                    Integer.toString(currentValue > 0 ? currentValue - 1 : currentValue)
            );

            updateLateReturnPrices();
        }
    }//GEN-LAST:event_buttonPrecosMultiplicadosMenosActionPerformed

    private void buttonPrecosMultiplicadosMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrecosMultiplicadosMaisActionPerformed
        if (((PriceCategoryTable) comboBoxCategoriaDePreco.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Favor selecionar uma categoria de preço, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            labelValuePrecosDosDiasMultiplicadosPor.setText(
                    Integer.toString(Integer.parseInt(labelValuePrecosDosDiasMultiplicadosPor.getText()) + 1)
            );

            updateLateReturnPrices();
        }
    }//GEN-LAST:event_buttonPrecosMultiplicadosMaisActionPerformed

    /**
     * tests only days, not price or anything else.
     * is not nice to have to create a PriceTable object just to compare their amountOfDays
     * attribute, therefore it wouldn't work if i used a custom equals(), that compares their
     * amountOfDays attribute, in the PriceTable object.
     *
     * @param days
     * @return
     */
    private boolean listPrecosContainsAmountOfDays(int days) {
        for (int i = 0; i < listPrecosModel.getSize(); i++) {
            if (((PriceTable) listPrecosModel.getElementAt(i)).getAmountOfDays() == days) {
                return true;
            }
        }

        return false;
    }

    /**
     * updating a local value inside the prices so that they will show the updated late return
     * prices in the list.
     */
    private void updateLateReturnPrices() {
        for (int i = 0; i < listPrecosModel.getSize(); i++) {

            ((PriceTable) listPrecosModel.getElementAt(i))
                    .setMultiplyBy(
                            Integer.parseInt(labelValuePrecosDosDiasMultiplicadosPor.getText())
                    );

        }

        //to refresh the list and show the updated values
        listPrecos.updateUI();
    }

    /**
     * checking if the description is already present in the comboBox list.
     * this comboBox list has all the priceCategories from the DB, priceCategories that are active
     * and inactive, therefore is the same as searching the DB, but faster.
     *
     * is not nice to have to create a PriceCategoryTable object just to compare their description
     * attribute, therefore it wouldn't work if i used a custom equals(), that compares their
     * description attribute, in the PriceCategoryTable object.
     *
     * @param description
     * @return
     */
    private boolean comboBoxCategoriaDePrecoContainsDescription(String description) {
        for (int i = 0; i < comboBoxCategoriaDePrecoDataList.size(); i++) {
            PriceCategoryTable currentPriceCategory = (PriceCategoryTable) comboBoxCategoriaDePrecoDataList.get(i);

            if (!currentPriceCategory.isEmptyString()
                    && currentPriceCategory.getDescription().equals(description)) {

                return true;
            }
        }

        return false;
    }

    /**
     * custom dispose() to ask if the user is sure, close the DB connection and call the main GUI
     * again.
     */
    @Override
    public void dispose() {
        if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja sair?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
            super.dispose();
        }
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
         * feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarCategoriaDePreco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarPreco;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCancelarAlteracao;
    private javax.swing.JButton buttonFinalizarAlteracao;
    private javax.swing.JButton buttonMaisDias;
    private javax.swing.JButton buttonMenosDias;
    private javax.swing.JButton buttonPrecosMultiplicadosMais;
    private javax.swing.JButton buttonPrecosMultiplicadosMenos;
    private javax.swing.JButton buttonRemoverPreco;
    private javax.swing.JCheckBox checkBoxCategoriaDePrecoAtiva;
//    private javax.swing.JComboBox comboBoxAlterarFilmes;
  //  private javax.swing.JComboBox comboBoxCategoriaDePreco;
    private javax.swing.JFormattedTextField formattedTextFieldFinePrice;
    private javax.swing.JFormattedTextField formattedTextFieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelAlterarFilmesComEstaCategoriaPara;
    private javax.swing.JLabel labelCategoriaDePreco;
    private javax.swing.JLabel labelCategoriaDePrecoAtiva;
    private javax.swing.JLabel labelDevolucaoAtrasada;
    private javax.swing.JLabel labelDias;
    private javax.swing.JLabel labelNovaDescricao;
    private javax.swing.JLabel labelNovasAnotacoes;
    private javax.swing.JLabel labelNovoPreco;
    private javax.swing.JLabel labelPrecos;
    private javax.swing.JLabel labelPrecosDosDiasMultiplicadosPor;
    private javax.swing.JLabel labelQuantidadeDeFilmesUsandoEstaCategoria;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelValorDaMulta;
    private javax.swing.JLabel labelValueDias;
    private javax.swing.JLabel labelValuePrecosDosDiasMultiplicadosPor;
    private javax.swing.JLabel labelValueQuantidadeDeFilmesUsandoEstaCategoria;
    private javax.swing.JList<String> listPrecos;
    private javax.swing.JTextArea textAreaNovasAnotacoes;
    private javax.swing.JTextField textFieldNovaDescricao;
    // End of variables declaration//GEN-END:variables
}
