/*
 * USING dbDesign10
 */

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class PagarDivida extends javax.swing.JFrame {
    private Connection conn;
    private Statement stmt;
    private PreparedStatement prepStmt;
    private ResultSet rs;

    /**
     * Vector is deprecated, but DefaultComboBoxModel uses it internally, and DefaultComboBoxModel
     * is recommended to be used in this situation, so there's no point in using something else here
     * because DefaultComboBoxModel will implement it as a Vector internally.
     */
    private Vector comboBoxClienteDataList;
    private AutoComboBox comboBoxCliente;
    private Vector comboBoxFormaDePagamentoDataList;
    private AutoComboBox comboBoxFormaDePagamento;

    private DefaultListModel listFormasDePagamentoModel;

    public PagarDivida() {
        comboBoxClienteDataList = new Vector();
        comboBoxCliente = new AutoComboBox(comboBoxClienteDataList);
        comboBoxFormaDePagamentoDataList = new Vector();
        comboBoxFormaDePagamento = new AutoComboBox(comboBoxFormaDePagamentoDataList);

        listFormasDePagamentoModel = new DefaultListModel();

        initComponents();

        listFormasDePagamento.setModel(listFormasDePagamentoModel);

        textAreaAnotacoes.setEditable(false);

        try {
            conn = DriverManager.getConnection("jdbc:sqlite:local/designedDb.db");
            stmt = conn.createStatement();
            stmt.setQueryTimeout(30);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        //populate comboBoxCliente
        comboBoxClienteDataList.add(new ClientTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_CLIENT"
                    + " ORDER BY CLI_FIRST_NAME"); //and last name as well
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                comboBoxClienteDataList.add(new ClientTable(
                        rs.getInt("CLI_ID"),
                        rs.getString("CLI_FIRST_NAME"),
                        rs.getString("CLI_LAST_NAME"),
                        rs.getString("CLI_CPF"),
                        rs.getLong("CLI_DATE_OF_BIRTH"),
                        rs.getLong("CLI_DATE_OF_ADMISSION"),
                        rs.getInt("CLI_ACTIVE"),
                        rs.getString("CLI_NOTES"),
                        rs.getLong("CLI_DEBT"),
                        rs.getInt("CLI_TOTAL_AMOUNT_OF_MOVIES_RENTED")
                ));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        comboBoxCliente.setDataList(comboBoxClienteDataList);

        //populate comboBoxFormaDePagamento
        comboBoxFormaDePagamentoDataList.add(new PaymentFormTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_PAYMENT_FORM"
                    + " WHERE PAY_FOR_ACTIVE = 1"
                    + " ORDER BY PAY_FOR_DESCRIPTION");
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                comboBoxFormaDePagamentoDataList.add(new PaymentFormTable(
                        rs.getInt("PAY_FOR_ID"),
                        rs.getString("PAY_FOR_DESCRIPTION"),
                        rs.getString("PAY_FOR_NOTES"),
                        rs.getInt("PAY_FOR_ACTIVE")
                ));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        comboBoxFormaDePagamento.setDataList(comboBoxFormaDePagamentoDataList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        buttonFinalizarPagamento = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        labelValorTotal = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        comboBoxCliente = new AutoComboBox(comboBoxClienteDataList);
        labelValueCpfDoCliente = new javax.swing.JLabel();
        labelCpfDoCliente = new javax.swing.JLabel();
        labelDataDeNascimento = new javax.swing.JLabel();
        labelValueDataDeNascimento = new javax.swing.JLabel();
        labelDataDoCadastro = new javax.swing.JLabel();
        labelValueDataDoCadastro = new javax.swing.JLabel();
        labelQuantidadeTotalDeFilmesEmprestados = new javax.swing.JLabel();
        labelValueValorTotal = new javax.swing.JLabel();
        labelFormasDePagamento = new javax.swing.JLabel();
        comboBoxFormaDePagamento = new AutoComboBox(comboBoxFormaDePagamentoDataList);
        jScrollPane2 = new javax.swing.JScrollPane();
        listFormasDePagamento = new javax.swing.JList<>();
        labelFormaDePagamento = new javax.swing.JLabel();
        buttonAdicionarFormaDePagamentoNaLista = new javax.swing.JButton();
        buttonRemoverFormaDePagamentoDaLista = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        buttonCancelarPagamento = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        labelValorSendoPago = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        labelValueQuantidadeTotalDeFilmesEmprestados = new javax.swing.JLabel();
        labelAnotacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaAnotacoes = new javax.swing.JTextArea();
        formattedTextFieldValorSendoPago = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(750, 600));

        buttonFinalizarPagamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonFinalizarPagamento.setText("Finalizar Pagamento");
        buttonFinalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarPagamentoActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitle.setText("Pagar Dívida");

        labelValorTotal.setText("Valor Total da Dívida :   R$");

        labelCliente.setText("* Cliente :");

        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxClienteActionPerformed(evt);
            }
        });

        labelValueCpfDoCliente.setText("0");

        labelCpfDoCliente.setText("CPF do Cliente :");

        labelDataDeNascimento.setText("Data de Nascimento :");

        labelValueDataDeNascimento.setText("0");

        labelDataDoCadastro.setText("Data do Cadastro :");

        labelValueDataDoCadastro.setText("0");

        labelQuantidadeTotalDeFilmesEmprestados.setText("Quantidade Total de Filmes Emprestados :");

        labelValueValorTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelValueValorTotal.setText("0.00");

        labelFormasDePagamento.setText("Formas de Pagamento :");

        comboBoxFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxFormaDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFormaDePagamentoActionPerformed(evt);
            }
        });

        listFormasDePagamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listFormasDePagamento);

        labelFormaDePagamento.setText("Forma de Pagamento :");

        buttonAdicionarFormaDePagamentoNaLista.setText("Adicionar Forma de Pagamento na Lista");
        buttonAdicionarFormaDePagamentoNaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarFormaDePagamentoNaListaActionPerformed(evt);
            }
        });

        buttonRemoverFormaDePagamentoDaLista.setText("Remover Forma de Pagamento da Lista");
        buttonRemoverFormaDePagamentoDaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverFormaDePagamentoDaListaActionPerformed(evt);
            }
        });

        buttonCancelarPagamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCancelarPagamento.setText("Cancelar Pagamento");
        buttonCancelarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarPagamentoActionPerformed(evt);
            }
        });

        labelValorSendoPago.setText("Valor Sendo Pago :   R$");

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        labelValueQuantidadeTotalDeFilmesEmprestados.setText("0");

        labelAnotacoes.setText("Anotações :");

        textAreaAnotacoes.setColumns(20);
        textAreaAnotacoes.setRows(5);
        jScrollPane1.setViewportView(textAreaAnotacoes);

        formattedTextFieldValorSendoPago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        formattedTextFieldValorSendoPago.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelAnotacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonRemoverFormaDePagamentoDaLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                                .addComponent(buttonAdicionarFormaDePagamentoNaLista))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFormaDePagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxFormaDePagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelQuantidadeTotalDeFilmesEmprestados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueQuantidadeTotalDeFilmesEmprestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDataDoCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueDataDoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDataDeNascimento)
                                .addGap(18, 18, 18)
                                .addComponent(labelValueDataDeNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCpfDoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueCpfDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(buttonBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFormasDePagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelValorSendoPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formattedTextFieldValorSendoPago)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCancelarPagamento)
                        .addGap(60, 60, 60)
                        .addComponent(buttonFinalizarPagamento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente)
                    .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar))
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfDoCliente)
                    .addComponent(labelValueCpfDoCliente))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDeNascimento)
                    .addComponent(labelValueDataDeNascimento))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDoCadastro)
                    .addComponent(labelValueDataDoCadastro))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidadeTotalDeFilmesEmprestados)
                    .addComponent(labelValueQuantidadeTotalDeFilmesEmprestados))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAnotacoes)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorTotal)
                    .addComponent(labelValueValorTotal))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorSendoPago)
                    .addComponent(formattedTextFieldValorSendoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormasDePagamento)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormaDePagamento)
                    .addComponent(comboBoxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionarFormaDePagamentoNaLista)
                    .addComponent(buttonRemoverFormaDePagamentoDaLista))
                .addGap(20, 20, 20)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFinalizarPagamento)
                    .addComponent(buttonCancelarPagamento))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarPagamentoActionPerformed
        ClientTable selectedClient = (ClientTable) comboBoxCliente.getSelectedItem();

        if (formattedTextFieldValorSendoPago.getText().trim().isEmpty()
                || new BigDecimal(formattedTextFieldValorSendoPago.getText()).compareTo(BigDecimal.ZERO) == 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Quitação\", favor inserir o valor sendo pago.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedClient.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Quitação\", favor selecionar um cliente, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValorSendoPago.getText())
                .compareTo(BigDecimal.ZERO) < 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nNão é possível inserir um valor negativo!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (listFormasDePagamento.getModel().getSize() == 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nA lista de formas de pagamento deve possuir pelo menos uma forma de pagamento!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValorSendoPago.getText())
                .compareTo(new BigDecimal(labelValueValorTotal.getText())) > 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "O valor máximo que pode ser pago é o valor da dívida: \"R$ " + labelValueValorTotal.getText() + "\"",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja finalizar?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                //update client
                prepStmt = conn.prepareStatement("UPDATE TB_CLIENT SET"
                        + " CLI_DEBT = ?" //1
                        + " WHERE CLI_ID = ?"); //2
                prepStmt.setLong(1,
                        new BigDecimal(labelValueValorTotal.getText())
                                .subtract(new BigDecimal(formattedTextFieldValorSendoPago.getText()))
                                .multiply(new BigDecimal(100))
                                .longValue()
                );
                prepStmt.setInt(2, selectedClient.getId());
                prepStmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Quitação da dívida bem sucedida.");
                new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
                super.dispose();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonFinalizarPagamentoActionPerformed

    private void comboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxClienteActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxClienteActionPerformed

    private void buttonAdicionarFormaDePagamentoNaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarFormaDePagamentoNaListaActionPerformed
        comboBoxFormaDePagamentoActionPerformed(evt); //to make sure it's selected

        PaymentFormTable selectedPaymentForm = (PaymentFormTable) comboBoxFormaDePagamento.getSelectedItem();

        if (((ClientTable) comboBoxCliente.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Adicionar Forma de Pagamento na Lista\", favor selecionar um cliente, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedPaymentForm.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Adicionar Forma de Pagamento na Lista\", favor selecionar uma forma de pagamento para adicionar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (listFormasDePagamentoModel.contains(selectedPaymentForm)) {

            JOptionPane.showMessageDialog(
                    null,
                    "Esta forma de pagamento já está na lista!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            listFormasDePagamentoModel.addElement(selectedPaymentForm);
        }
    }//GEN-LAST:event_buttonAdicionarFormaDePagamentoNaListaActionPerformed

    private void buttonRemoverFormaDePagamentoDaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverFormaDePagamentoDaListaActionPerformed
        int selectedIndex = listFormasDePagamento.getSelectedIndex();

        if (((ClientTable) comboBoxCliente.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Forma de Pagamento da Lista\", favor selecionar um cliente, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedIndex == -1) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Forma de Pagamento da Lista\", favor selecionar uma forma de pagamento, da lista de formas de pagamento, para remover.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja remover a forma de pagamento selecionada?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            listFormasDePagamentoModel.remove(selectedIndex);
        }
    }//GEN-LAST:event_buttonRemoverFormaDePagamentoDaListaActionPerformed

    private void comboBoxFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFormaDePagamentoActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxFormaDePagamentoActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        ClientTable selectedClient = (ClientTable) comboBoxCliente.getSelectedItem();

        if (selectedClient.isEmptyString()) {

            JOptionPane.showMessageDialog(
                null,
                "Antes de clicar em \"Buscar Cliente\", favor selecionar um cliente para buscar.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );

        } else {
            labelValueCpfDoCliente.setText(selectedClient.getCpf());
            labelValueDataDeNascimento.setText(String.format("%1$td / %1$tm / %1$tY", new Date(selectedClient.getDateOfBirth())));
            labelValueDataDoCadastro.setText(String.format("%1$td / %1$tm / %1$tY", new Date(selectedClient.getDateOfAdmission())));
            labelValueQuantidadeTotalDeFilmesEmprestados.setText(
                selectedClient.getTotalAmountOfMoviesRented()
                + " filme(s)"
            );
            labelValueValorTotal.setText(
                new DecimalFormat("#0.00").format(
                    BigDecimal.valueOf(selectedClient.getDebt())
                    .divide(new BigDecimal(100)))
            );
            textAreaAnotacoes.setText(selectedClient.getNotes());

            formattedTextFieldValorSendoPago.setText(labelValueValorTotal.getText());
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonCancelarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarPagamentoActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarPagamentoActionPerformed

    /**
     * custom dispose() to ask if the user is sure, close the DB connection and call the main GUI
     * again.
     */
    @Override
    public void dispose() {
        if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja sair?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
            super.dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarDivida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarFormaDePagamentoNaLista;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCancelarPagamento;
    private javax.swing.JButton buttonFinalizarPagamento;
    private javax.swing.JButton buttonRemoverFormaDePagamentoDaLista;
//    private javax.swing.JComboBox comboBoxCliente;
  //  private javax.swing.JComboBox comboBoxFormaDePagamento;
    private javax.swing.JFormattedTextField formattedTextFieldValorSendoPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelAnotacoes;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelCpfDoCliente;
    private javax.swing.JLabel labelDataDeNascimento;
    private javax.swing.JLabel labelDataDoCadastro;
    private javax.swing.JLabel labelFormaDePagamento;
    private javax.swing.JLabel labelFormasDePagamento;
    private javax.swing.JLabel labelQuantidadeTotalDeFilmesEmprestados;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelValorSendoPago;
    private javax.swing.JLabel labelValorTotal;
    private javax.swing.JLabel labelValueCpfDoCliente;
    private javax.swing.JLabel labelValueDataDeNascimento;
    private javax.swing.JLabel labelValueDataDoCadastro;
    private javax.swing.JLabel labelValueQuantidadeTotalDeFilmesEmprestados;
    private javax.swing.JLabel labelValueValorTotal;
    private javax.swing.JList<String> listFormasDePagamento;
    private javax.swing.JTextArea textAreaAnotacoes;
    // End of variables declaration//GEN-END:variables
}
