/*
 * USING dbDesign7
 */

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.time.Duration;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import static java.lang.Math.toIntExact;

public class RealizarDevolucao extends javax.swing.JFrame {
    private Connection conn;
    private Statement stmt;
    private PreparedStatement prepStmt;
    private ResultSet rs;

    /**
     * Vector is deprecated, but DefaultComboBoxModel uses it internally, and DefaultComboBoxModel
     * is recommended to be used in this situation, so there's no point in using something else here
     * because DefaultComboBoxModel will implement it as a Vector internally.
     */
    private Vector comboBoxClienteDataList;
    private AutoComboBox comboBoxCliente;
    private Vector comboBoxEmprestimoDataList;
    private AutoComboBox comboBoxEmprestimo;
    private Vector comboBoxFormaDePagamentoDataList;
    private AutoComboBox comboBoxFormaDePagamento;

    private DefaultListModel listFilmesModel;
    private DefaultListModel listFormasDePagamentoModel;

    public RealizarDevolucao() {
        comboBoxClienteDataList = new Vector();
        comboBoxCliente = new AutoComboBox(comboBoxClienteDataList);
        comboBoxEmprestimoDataList = new Vector();
        comboBoxEmprestimo = new AutoComboBox(comboBoxEmprestimoDataList);
        comboBoxFormaDePagamentoDataList = new Vector();
        comboBoxFormaDePagamento = new AutoComboBox(comboBoxFormaDePagamentoDataList);

        listFilmesModel = new DefaultListModel();
        listFormasDePagamentoModel = new DefaultListModel();

        initComponents();

        listFilmes.setModel(listFilmesModel);
        listFormasDePagamento.setModel(listFormasDePagamentoModel);

        textAreaAnotacoes.setEditable(false);

        try {
            conn = DriverManager.getConnection("jdbc:sqlite:local/designedDb.db");
            stmt = conn.createStatement();
            stmt.setQueryTimeout(30);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        //populate comboBoxCliente
        comboBoxClienteDataList.add(new ClientTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_CLIENT"
                    + " ORDER BY CLI_FIRST_NAME"); //and last name as well
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                comboBoxClienteDataList.add(new ClientTable(
                        rs.getInt("CLI_ID"),
                        rs.getString("CLI_FIRST_NAME"),
                        rs.getString("CLI_LAST_NAME"),
                        rs.getString("CLI_CPF"),
                        rs.getLong("CLI_DATE_OF_BIRTH"),
                        rs.getLong("CLI_DATE_OF_ADMISSION"),
                        rs.getInt("CLI_ACTIVE"),
                        rs.getString("CLI_NOTES"),
                        rs.getLong("CLI_DEBT"),
                        rs.getInt("CLI_TOTAL_AMOUNT_OF_MOVIES_RENTED")
                ));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        comboBoxCliente.setDataList(comboBoxClienteDataList);

        //populate comboBoxFormaDePagamento
        comboBoxFormaDePagamentoDataList.add(new PaymentFormTable()); //insert the first empty string
        try {
            prepStmt = conn.prepareStatement("SELECT *"
                    + " FROM TB_PAYMENT_FORM"
                    + " WHERE PAY_FOR_ACTIVE = 1"
                    + " ORDER BY PAY_FOR_DESCRIPTION");
            rs = prepStmt.executeQuery();

            while (rs.next()) {
                comboBoxFormaDePagamentoDataList.add(new PaymentFormTable(
                        rs.getInt("PAY_FOR_ID"),
                        rs.getString("PAY_FOR_DESCRIPTION"),
                        rs.getString("PAY_FOR_NOTES"),
                        rs.getInt("PAY_FOR_ACTIVE")
                ));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        comboBoxFormaDePagamento.setDataList(comboBoxFormaDePagamentoDataList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        buttonFinalizarDevolucao = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        labelFilmes = new javax.swing.JLabel();
        labelValorTotal = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        comboBoxCliente = new AutoComboBox(comboBoxClienteDataList);
        labelValueCpfDoCliente = new javax.swing.JLabel();
        labelCpfDoCliente = new javax.swing.JLabel();
        labelDividaDoCliente = new javax.swing.JLabel();
        labelValueDividaDoCliente = new javax.swing.JLabel();
        labelDataDeNascimento = new javax.swing.JLabel();
        labelValueDataDeNascimento = new javax.swing.JLabel();
        labelDataDoCadastro = new javax.swing.JLabel();
        labelValueDataDoCadastro = new javax.swing.JLabel();
        labelQuantidadeTotalDeFilmesEmprestados = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listFilmes = new javax.swing.JList<>();
        buttonRemoverFilmeDaLista = new javax.swing.JButton();
        labelValueValorTotal = new javax.swing.JLabel();
        labelFormasDePagamento = new javax.swing.JLabel();
        comboBoxFormaDePagamento = new AutoComboBox(comboBoxFormaDePagamentoDataList);
        jScrollPane2 = new javax.swing.JScrollPane();
        listFormasDePagamento = new javax.swing.JList<>();
        labelFormaDePagamento = new javax.swing.JLabel();
        buttonAdicionarFormaDePagamentoNaLista = new javax.swing.JButton();
        buttonRemoverFormaDePagamentoDaLista = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        buttonCancelarDevolucao = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        labelValorSendoPago = new javax.swing.JLabel();
        buttonBuscarCliente = new javax.swing.JButton();
        labelValueQuantidadeTotalDeFilmesEmprestados = new javax.swing.JLabel();
        labelAnotacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaAnotacoes = new javax.swing.JTextArea();
        formattedTextFieldValorSendoPago = new javax.swing.JFormattedTextField();
        labelEmprestimo = new javax.swing.JLabel();
        comboBoxEmprestimo = new AutoComboBox(comboBoxEmprestimoDataList);
        buttonBuscarEmprestimo = new javax.swing.JButton();
        labelDiasDeAtraso = new javax.swing.JLabel();
        labelValueDiasDeAtraso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(807, 679));

        jScrollPane4.setPreferredSize(new java.awt.Dimension(817, 679));

        buttonFinalizarDevolucao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonFinalizarDevolucao.setText("Finalizar Devolução");
        buttonFinalizarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarDevolucaoActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitle.setText("Realizar Devolução");

        labelFilmes.setText("* Devolvendo os Filmes :");

        labelValorTotal.setText("Valor Total :   R$");

        labelCliente.setText("* Cliente :");

        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxClienteActionPerformed(evt);
            }
        });

        labelValueCpfDoCliente.setText("0");

        labelCpfDoCliente.setText("CPF do Cliente :");

        labelDividaDoCliente.setText("Dívida do Cliente :   R$");

        labelValueDividaDoCliente.setText("0");

        labelDataDeNascimento.setText("Data de Nascimento :");

        labelValueDataDeNascimento.setText("0");

        labelDataDoCadastro.setText("Data do Cadastro :");

        labelValueDataDoCadastro.setText("0");

        labelQuantidadeTotalDeFilmesEmprestados.setText("Quantidade Total de Filmes Emprestados :");

        listFilmes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listFilmes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listFilmes);

        buttonRemoverFilmeDaLista.setText("Remover Filme da Lista");
        buttonRemoverFilmeDaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverFilmeDaListaActionPerformed(evt);
            }
        });

        labelValueValorTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelValueValorTotal.setText("0.00");

        labelFormasDePagamento.setText("Formas de Pagamento :");

        comboBoxFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxFormaDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFormaDePagamentoActionPerformed(evt);
            }
        });

        listFormasDePagamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listFormasDePagamento);

        labelFormaDePagamento.setText("Forma de Pagamento :");

        buttonAdicionarFormaDePagamentoNaLista.setText("Adicionar Forma de Pagamento na Lista");
        buttonAdicionarFormaDePagamentoNaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarFormaDePagamentoNaListaActionPerformed(evt);
            }
        });

        buttonRemoverFormaDePagamentoDaLista.setText("Remover Forma de Pagamento da Lista");
        buttonRemoverFormaDePagamentoDaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverFormaDePagamentoDaListaActionPerformed(evt);
            }
        });

        buttonCancelarDevolucao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonCancelarDevolucao.setText("Cancelar Devolução");
        buttonCancelarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarDevolucaoActionPerformed(evt);
            }
        });

        labelValorSendoPago.setText("Valor Sendo Pago :   R$");

        buttonBuscarCliente.setText("Buscar Cliente");
        buttonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarClienteActionPerformed(evt);
            }
        });

        labelValueQuantidadeTotalDeFilmesEmprestados.setText("0");

        labelAnotacoes.setText("Anotações :");

        textAreaAnotacoes.setColumns(20);
        textAreaAnotacoes.setRows(5);
        jScrollPane1.setViewportView(textAreaAnotacoes);

        formattedTextFieldValorSendoPago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        formattedTextFieldValorSendoPago.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        labelEmprestimo.setText("* Empréstimo :");

        comboBoxEmprestimo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEmprestimoActionPerformed(evt);
            }
        });

        buttonBuscarEmprestimo.setText("Buscar Empréstimo");
        buttonBuscarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarEmprestimoActionPerformed(evt);
            }
        });

        labelDiasDeAtraso.setText("Dias de atraso :");

        labelValueDiasDeAtraso.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelAnotacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonRemoverFormaDePagamentoDaLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonAdicionarFormaDePagamentoNaLista))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFormaDePagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxFormaDePagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelQuantidadeTotalDeFilmesEmprestados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueQuantidadeTotalDeFilmesEmprestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDataDoCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueDataDoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDataDeNascimento)
                                .addGap(18, 18, 18)
                                .addComponent(labelValueDataDeNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDividaDoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelValueDividaDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFilmes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCpfDoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueCpfDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(buttonBuscarCliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFormasDePagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelValorSendoPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formattedTextFieldValorSendoPago))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelEmprestimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxEmprestimo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(buttonBuscarEmprestimo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDiasDeAtraso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelValueDiasDeAtraso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonRemoverFilmeDaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCancelarDevolucao)
                        .addGap(60, 60, 60)
                        .addComponent(buttonFinalizarDevolucao)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente)
                    .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarCliente))
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmprestimo)
                    .addComponent(comboBoxEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarEmprestimo))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfDoCliente)
                    .addComponent(labelValueCpfDoCliente))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDeNascimento)
                    .addComponent(labelValueDataDeNascimento))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDoCadastro)
                    .addComponent(labelValueDataDoCadastro))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidadeTotalDeFilmesEmprestados)
                    .addComponent(labelValueQuantidadeTotalDeFilmesEmprestados))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDividaDoCliente)
                    .addComponent(labelValueDividaDoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAnotacoes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiasDeAtraso)
                    .addComponent(labelValueDiasDeAtraso))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFilmes)
                    .addComponent(jScrollPane3))
                .addGap(10, 10, 10)
                .addComponent(buttonRemoverFilmeDaLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorTotal)
                    .addComponent(labelValueValorTotal))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorSendoPago)
                    .addComponent(formattedTextFieldValorSendoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormasDePagamento)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormaDePagamento)
                    .addComponent(comboBoxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionarFormaDePagamentoNaLista)
                    .addComponent(buttonRemoverFormaDePagamentoDaLista))
                .addGap(20, 20, 20)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFinalizarDevolucao)
                    .addComponent(buttonCancelarDevolucao))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinalizarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarDevolucaoActionPerformed
        ClientTable selectedClient = (ClientTable) comboBoxCliente.getSelectedItem();
        RentalTable selectedRental = (RentalTable) comboBoxEmprestimo.getSelectedItem();

        if (formattedTextFieldValorSendoPago.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Devolução\", favor inserir o valor sendo pago. Se o pagamento não vai ser realizado agora, favor inserir \"0\"",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedClient.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Finalizar Devolução\", favor selecionar um cliente, e clicar em \"Buscar Cliente\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (listFilmes.getModel().getSize() == 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nA lista de filmes deve possuir pelo menos um filme!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValorSendoPago.getText())
                .compareTo(BigDecimal.ZERO) < 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nNão é possível inserir um valor negativo!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValorSendoPago.getText()).compareTo(BigDecimal.ZERO) == 0
                && listFormasDePagamento.getModel().getSize() > 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nSe o pagamento vai ser realizado agora, favor inserir o valor sendo pago!"
                    + "\nSe o pagamento não vai ser realizado agora, a lista de formas de pagamento deve estar vazia!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValorSendoPago.getText()).compareTo(BigDecimal.ZERO) > 0
                && listFormasDePagamento.getModel().getSize() == 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "ERRO!\nSe o pagamento vai ser realizado agora, a lista de formas de pagamento deve possuir pelo menos uma forma de pagamento!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (new BigDecimal(formattedTextFieldValorSendoPago.getText())
                .compareTo(new BigDecimal(labelValueValorTotal.getText())) > 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "O valor máximo que pode ser pago é o valor do empréstimo: \"R$ " + labelValueValorTotal.getText() + "\"",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja finalizar?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                //REMEMBER TO GET FOR WINDOWS
                //get date from the OS
                Date currentDate = new Date(); //can use getTime if is not showing right

                //if all the movies, in the rental, are being returned
                if (listFilmes.getModel().getSize() == selectedRental.getAmountOfMovies()) {
                    //update rental
                    prepStmt = conn.prepareStatement("UPDATE TB_RENTAL SET "
                            + "REN_DATE_END = ?," //1
                            + "REN_ACTIVE = ?," //2
                            + "REN_AMOUNT_OF_DAYS = ?," //3
                            + "REN_TOTAL_PRICE = ?" //4
                            + " WHERE REN_ID = ?"); //5
                    prepStmt.setLong(1, currentDate.getTime());
                    prepStmt.setLong(2, 0);
                    prepStmt.setInt(3, selectedRental.getAmountOfDays());
                    prepStmt.setLong(4,
                            new BigDecimal(labelValueValorTotal.getText())
                                    .multiply(new BigDecimal(100))
                                    .longValue()
                    );
                    prepStmt.setInt(5, selectedRental.getId());
                    prepStmt.executeUpdate();

                    //if the client didnt pay everything
                    if (new BigDecimal(formattedTextFieldValorSendoPago.getText())
                            .compareTo(new BigDecimal(labelValueValorTotal.getText())) < 0) {

                        //update client
                        prepStmt = conn.prepareStatement("UPDATE TB_CLIENT SET"
                                + " CLI_DEBT = ?" //1
                                + " WHERE CLI_ID = ?"); //2
                        prepStmt.setLong(1,
                                new BigDecimal(labelValueValorTotal.getText())
                                        .subtract(new BigDecimal(formattedTextFieldValorSendoPago.getText()))
                                        .multiply(new BigDecimal(100))
                                        .longValue()
                        );
                        prepStmt.setInt(2, selectedClient.getId());
                        prepStmt.executeUpdate();
                    }
                }

                //for each movie
                for (int i = 0; i < listFilmesModel.getSize(); i++) {
                    MovieTable currentMovie = (MovieTable) listFilmesModel.getElementAt(i);

                    //make the movie available
                    prepStmt = conn.prepareStatement("UPDATE TB_MOVIE SET"
                            + " MOV_AVAILABLE = ?" //1
                            + " WHERE MOV_ID = ?"); //2
                    prepStmt.setInt(1, 1);
                    prepStmt.setInt(2, currentMovie.getId());
                    prepStmt.executeUpdate();
                }

                //for each formOfPayment
                for (int i = 0; i < listFormasDePagamentoModel.getSize(); i++) {
                    PaymentFormTable currentPaymentForm = (PaymentFormTable) listFormasDePagamentoModel.getElementAt(i);

                    prepStmt = conn.prepareStatement("INSERT INTO TB_RENTAL_PAYMENT_FORM("
                            + "REN_PAY_FOR_TB_RENTAL_ID," //1
                            + "REN_PAY_FOR_TB_PAYMENT_FORM_ID" //2
                            + ") VALUES(?,?)");
                    prepStmt.setInt(1, selectedRental.getId());
                    prepStmt.setInt(2, currentPaymentForm.getId());
                    prepStmt.executeUpdate();
                }

                JOptionPane.showMessageDialog(null, "Devolução do Empréstimo bem sucedida.");
                new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
                super.dispose();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonFinalizarDevolucaoActionPerformed

    private void comboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxClienteActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxClienteActionPerformed

    private void buttonRemoverFilmeDaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverFilmeDaListaActionPerformed
        int selectedIndex = listFilmes.getSelectedIndex();

        if (((ClientTable) comboBoxCliente.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Filme da Lista\", favor selecionar um cliente, e clicar em \"Buscar Cliente\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (((RentalTable) comboBoxEmprestimo.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Filme da Lista\", favor selecionar um empréstimo, e clicar em \"Buscar Empréstimo\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedIndex == -1) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Filme da Lista\", favor selecionar um filme, da lista de filmes, para remover.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja remover o filme selecionado?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            listFilmesModel.remove(selectedIndex);
            updateLabelValueValorTotal();
        }
    }//GEN-LAST:event_buttonRemoverFilmeDaListaActionPerformed

    private void buttonAdicionarFormaDePagamentoNaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarFormaDePagamentoNaListaActionPerformed
        comboBoxFormaDePagamentoActionPerformed(evt); //to make sure it's selected

        PaymentFormTable selectedPaymentForm = (PaymentFormTable) comboBoxFormaDePagamento.getSelectedItem();

        if (((ClientTable) comboBoxCliente.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Adicionar Forma de Pagamento na Lista\", favor selecionar um cliente, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedPaymentForm.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Adicionar Forma de Pagamento na Lista\", favor selecionar uma forma de pagamento para adicionar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (listFormasDePagamentoModel.contains(selectedPaymentForm)) {

            JOptionPane.showMessageDialog(
                    null,
                    "Esta forma de pagamento já está na lista!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            listFormasDePagamentoModel.addElement(selectedPaymentForm);
        }
    }//GEN-LAST:event_buttonAdicionarFormaDePagamentoNaListaActionPerformed

    private void buttonRemoverFormaDePagamentoDaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverFormaDePagamentoDaListaActionPerformed
        int selectedIndex = listFormasDePagamento.getSelectedIndex();

        if (((ClientTable) comboBoxCliente.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Forma de Pagamento da Lista\", favor selecionar um cliente, e clicar em \"Buscar\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedIndex == -1) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Remover Forma de Pagamento da Lista\", favor selecionar uma forma de pagamento, da lista de formas de pagamento, para remover.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja remover a forma de pagamento selecionada?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            listFormasDePagamentoModel.remove(selectedIndex);
        }
    }//GEN-LAST:event_buttonRemoverFormaDePagamentoDaListaActionPerformed

    private void comboBoxFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFormaDePagamentoActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxFormaDePagamentoActionPerformed

    private void comboBoxEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEmprestimoActionPerformed
        //this was intentional, to make sure it's selected.
    }//GEN-LAST:event_comboBoxEmprestimoActionPerformed

    private void buttonBuscarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarEmprestimoActionPerformed
        RentalTable selectedRental = (RentalTable) comboBoxEmprestimo.getSelectedItem();

        if (((ClientTable) comboBoxCliente.getSelectedItem()).isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Buscar Empréstimo\", favor selecionar um cliente, e clicar em \"Buscar Cliente\".",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else if (selectedRental.isEmptyString()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Antes de clicar em \"Buscar Empréstimo\", favor selecionar um empréstimo para buscar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );

        } else {
            listFilmesModel.clear();

            /*
             * populate listFilmes.
             * 
             * " WHERE MOV_AVAILABLE = 0" because the client may want to return some movies, of the
             * rent, before the due date, therefore some of the movies connected to the rent may
             * already be available, because the client returned them already.
             *
             * OBS: i'm using this indentation in the string instead of it being before the "+"
             * so that the IDE wont pull it back when i use the autoFormat from the IDE.
             */
            try {
                prepStmt = conn.prepareStatement("SELECT *"
                        + " FROM TB_MOVIE"
                        + " WHERE MOV_AVAILABLE = 0"
                        + " AND MOV_ID IN ("
                        + "                     SELECT REN_MOV_TB_MOVIE_ID"
                        + "                     FROM TB_RENTAL_MOVIE"
                        + "                     WHERE REN_MOV_TB_RENTAL_ID = ?" //1
                        + ")");
                prepStmt.setInt(1, selectedRental.getId());
                rs = prepStmt.executeQuery();

                while (rs.next()) {
                    listFilmesModel.addElement(new MovieTable(
                            rs.getInt("MOV_ID"),
                            rs.getString("MOV_NAME"),
                            rs.getString("MOV_YEAR_OF_RELEASE"),
                            rs.getLong("MOV_DATE_OF_ACQUISITION"),
                            rs.getString("MOV_DESCRIPTION"),
                            rs.getInt("MOV_AVAILABLE"),
                            rs.getString("MOV_NOTES"),
                            rs.getString("MOV_KIND_OF_MEDIA"),
                            rs.getInt("MOV_DAMAGED"),
                            rs.getInt("MOV_ACTIVE"),
                            rs.getInt("MOV_TB_PRICE_CATEGORY_ID")
                    ));
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

            labelValueDiasDeAtraso.setText(
                    (selectedRental.getAmountOfDays() > selectedRental.getAmountOfDaysPredicted()
                    ? selectedRental.getAmountOfDays() - selectedRental.getAmountOfDaysPredicted()
                    : "0") + " dia(s)"
            );

            updateLabelValueValorTotal();
        }
    }//GEN-LAST:event_buttonBuscarEmprestimoActionPerformed

    private void buttonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarClienteActionPerformed
        ClientTable selectedClient = (ClientTable) comboBoxCliente.getSelectedItem();

        if (selectedClient.isEmptyString()) {

            JOptionPane.showMessageDialog(
                null,
                "Antes de clicar em \"Buscar Cliente\", favor selecionar um cliente para buscar.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );

        } else {
            listFilmesModel.clear();
            comboBoxEmprestimoDataList.clear();

            //REMEMBER TO GET FOR WINDOWS
            //get date from the OS
            Date currentDate = new Date(); //can use getTime if is not showing right

            labelValueCpfDoCliente.setText(selectedClient.getCpf());
            labelValueDataDeNascimento.setText(String.format("%1$td / %1$tm / %1$tY", new Date(selectedClient.getDateOfBirth())));
            labelValueDataDoCadastro.setText(String.format("%1$td / %1$tm / %1$tY", new Date(selectedClient.getDateOfAdmission())));
            labelValueQuantidadeTotalDeFilmesEmprestados.setText(
                selectedClient.getTotalAmountOfMoviesRented()
                + " filme(s)"
            );
            labelValueDividaDoCliente.setText(
                new DecimalFormat("#0.00").format(
                    BigDecimal.valueOf(selectedClient.getDebt())
                    .divide(new BigDecimal(100)))
            );
            textAreaAnotacoes.setText(selectedClient.getNotes());

            formattedTextFieldValorSendoPago.setText("0.00");

            //populate comboBoxEmprestimo
            comboBoxEmprestimoDataList.add(new RentalTable()); //insert the first empty string
            try {
                prepStmt = conn.prepareStatement("SELECT *"
                        + " FROM TB_RENTAL"
                        + " WHERE REN_ACTIVE = ?" //1
                        + " AND REN_TB_CLIENT_ID = ?" //2
                        + " ORDER BY REN_DATE_END_PREDICTED");
                prepStmt.setInt(1, 1);
                prepStmt.setInt(2, selectedClient.getId());
                rs = prepStmt.executeQuery();

                while (rs.next()) {
                    long dateBegin = rs.getLong("REN_DATE_BEGIN");

                    comboBoxEmprestimoDataList.add(new RentalTable(
                            rs.getInt("REN_ID"),
                            dateBegin,
                            rs.getLong("REN_DATE_END_PREDICTED"),
                            currentDate.getTime(),
                            rs.getInt("REN_ACTIVE"),
                            rs.getInt("REN_AMOUNT_OF_MOVIES"),
                            rs.getInt("REN_AMOUNT_OF_DAYS_PREDICTED"),
                            toIntExact(
                                    Duration.between(
                                            new Date(dateBegin).toInstant(),
                                            currentDate.toInstant()
                                    ).toDays()
                            ),
                            rs.getLong("REN_TOTAL_PRICE_PREDICTED"),
                            rs.getInt("REN_TB_CLIENT_ID")
                    ));
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            comboBoxEmprestimo.setDataList(comboBoxEmprestimoDataList);
        }
    }//GEN-LAST:event_buttonBuscarClienteActionPerformed

    private void buttonCancelarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarDevolucaoActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarDevolucaoActionPerformed

    private Long getMoviePrice(int priceCategoryID, int amountOfDays) {
        Long price = -1L;

        try {
            prepStmt = conn.prepareStatement("SELECT PRI_PRICE"
                    + " FROM TB_PRICE"
                    + " WHERE PRI_AMOUNT_OF_DAYS = ?" //1
                    + " AND PRI_TB_PRICE_CATEGORY_ID = ?"); //2
            prepStmt.setInt(1, amountOfDays);
            prepStmt.setInt(2, priceCategoryID);
            rs = prepStmt.executeQuery();

            if (rs.next()) {
                price = rs.getLong("PRI_PRICE");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        return price;
    }

    private String updateLabelValueValorTotal() {
        RentalTable selectedRental = (RentalTable) comboBoxEmprestimo.getSelectedItem();
        Long totalPrice = 0L;

        //this is updating the valorTotalValueLabel
        //by getting the price of each movie in the filmesList from the db everytime, it's
        //costly in resources if the filmesList is long, but most of the time it
        //will be 0 < size < 3 tops. i could implement a list of the prices of the movies currently
        //in the list instead of getting it again from the db, but since the list wont be long most
        //of the time and this teacher apparently doesnt care about code, it's not worth it atm.
        for (int i = 0; i < listFilmesModel.getSize(); i++) {
            MovieTable currentMovie = (MovieTable) listFilmesModel.getElementAt(i);

            Long moviePricePredictedReturn;
            Long finePrice = 0L;
            int multiplyBy = 0;
            Long moviePriceLateReturn = 0L;

            int amountOfDaysPredicted = selectedRental.getAmountOfDaysPredicted();
            moviePricePredictedReturn = getMoviePrice(currentMovie.getTbPriceCategoryId(), amountOfDaysPredicted);

            /*
             * if the priceCategory of the movie doesnt have a price for the amountOfDays, find a
             * day, lower than the current amounrOfDays, that has a price.
             */
            while (moviePricePredictedReturn.equals(new Long("-1")) && amountOfDaysPredicted > 0) {
                amountOfDaysPredicted--;

                moviePricePredictedReturn = getMoviePrice(currentMovie.getTbPriceCategoryId(), amountOfDaysPredicted);
            }

            if (moviePricePredictedReturn.equals(new Long("-1")) && amountOfDaysPredicted == 0) {
                moviePricePredictedReturn = 0L;
            }

            //if this is a late return
            int amountOfDaysAfterPredictedReturn = selectedRental.getAmountOfDays() - selectedRental.getAmountOfDaysPredicted();
            if (amountOfDaysAfterPredictedReturn > 0) {
                //get data from the priceCategory of the current movie
                try {
                    prepStmt = conn.prepareStatement("SELECT PRI_CAT_FINE_PRICE,"
                            + " PRI_CAT_MULTIPLY_BY"
                            + " FROM TB_PRICE_CATEGORY"
                            + " WHERE PRI_CAT_ID = ?"); //1
                    prepStmt.setInt(1, currentMovie.getTbPriceCategoryId());
                    rs = prepStmt.executeQuery();

                    if (rs.next()) {
                        finePrice = rs.getLong("PRI_CAT_FINE_PRICE");
                        multiplyBy = rs.getInt("PRI_CAT_MULTIPLY_BY");
                    }
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }

                //get the price for the days after the predicted return
                moviePriceLateReturn = getMoviePrice(currentMovie.getTbPriceCategoryId(), amountOfDaysAfterPredictedReturn);

                /*
                 * if the priceCategory of the movie doesnt have a price for the amountOfDays, find a
                 * day, lower than the current amounrOfDays, that has a price.
                 */
                while (moviePriceLateReturn.equals(new Long("-1")) && amountOfDaysAfterPredictedReturn > 0) {
                    amountOfDaysAfterPredictedReturn--;

                    moviePriceLateReturn = getMoviePrice(currentMovie.getTbPriceCategoryId(), amountOfDaysAfterPredictedReturn);
                }

                if (moviePriceLateReturn.equals(new Long("-1")) && amountOfDaysAfterPredictedReturn == 0) {
                    moviePriceLateReturn = 0L;
                }
            }

            totalPrice += moviePricePredictedReturn + finePrice + moviePriceLateReturn * multiplyBy;
        }
        labelValueValorTotal.setText(
                new DecimalFormat("#0.00").format(
                        BigDecimal.valueOf(totalPrice)
                                .divide(new BigDecimal(100))
                )
        );

        return "";
    }

    /**
     * custom dispose() to ask if the user is sure, close the DB connection and call the main GUI
     * again.
     */
    @Override
    public void dispose() {
        if (JOptionPane.showOptionDialog(
                null,
                "Tem certeza que deseja sair?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Sim", "Não"},
                "Sim") == JOptionPane.YES_OPTION) {

            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            new GerenciadorDeEmprestimosDeFilmes().setVisible(true);
            super.dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarDevolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarFormaDePagamentoNaLista;
    private javax.swing.JButton buttonBuscarCliente;
    private javax.swing.JButton buttonBuscarEmprestimo;
    private javax.swing.JButton buttonCancelarDevolucao;
    private javax.swing.JButton buttonFinalizarDevolucao;
    private javax.swing.JButton buttonRemoverFilmeDaLista;
    private javax.swing.JButton buttonRemoverFormaDePagamentoDaLista;
//    private javax.swing.JComboBox comboBoxCliente;
  //  private javax.swing.JComboBox comboBoxEmprestimo;
    //private javax.swing.JComboBox comboBoxFormaDePagamento;
    private javax.swing.JFormattedTextField formattedTextFieldValorSendoPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelAnotacoes;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelCpfDoCliente;
    private javax.swing.JLabel labelDataDeNascimento;
    private javax.swing.JLabel labelDataDoCadastro;
    private javax.swing.JLabel labelDiasDeAtraso;
    private javax.swing.JLabel labelDividaDoCliente;
    private javax.swing.JLabel labelEmprestimo;
    private javax.swing.JLabel labelFilmes;
    private javax.swing.JLabel labelFormaDePagamento;
    private javax.swing.JLabel labelFormasDePagamento;
    private javax.swing.JLabel labelQuantidadeTotalDeFilmesEmprestados;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelValorSendoPago;
    private javax.swing.JLabel labelValorTotal;
    private javax.swing.JLabel labelValueCpfDoCliente;
    private javax.swing.JLabel labelValueDataDeNascimento;
    private javax.swing.JLabel labelValueDataDoCadastro;
    private javax.swing.JLabel labelValueDiasDeAtraso;
    private javax.swing.JLabel labelValueDividaDoCliente;
    private javax.swing.JLabel labelValueQuantidadeTotalDeFilmesEmprestados;
    private javax.swing.JLabel labelValueValorTotal;
    private javax.swing.JList<String> listFilmes;
    private javax.swing.JList<String> listFormasDePagamento;
    private javax.swing.JTextArea textAreaAnotacoes;
    // End of variables declaration//GEN-END:variables
}
